version: '3.9'

services:
  db:
    restart: always
    image: postgres:15.0-alpine
    container_name: agro_db
    env_file:
      - .env.docker
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mail_app" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend_agro:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8002:8000'
    volumes:
      - .env.docker:/code/.env
    command: >
      bash -c "uvicorn app:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: